- name: Download node exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-armv7.tar.gz
    dest: /tmp/node_exporter-1.3.1.linux-armv7.tar.gz
  tags:
  - install

- name: Untar File
  unarchive:
    src: /tmp/node_exporter-1.3.1.linux-armv7.tar.gz
    dest: /tmp/
    remote_src: true

- name: Remove old folder if present
  file:
    state: absent
    path: /opt/node_exporter
  tags:
  - install

- name: Move install folder
  command: mv /tmp/node_exporter-1.3.1.linux-armv7 /opt/node_exporter
  tags:
  - install

- name: Create node_exporter User
  user:
    state: present
    name: node_exporter
  tags:
  - install

- name: Set Permissions on node_exporter
  file:
    path: /opt/node_exporter
    owner: node_exporter
    recurse: true
  tags:
  - install

- name: Copy Unit File
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
  tags:
  - install

- name: Enable/Start node_exporter
  systemd:
    daemon_reload: true
    state: restarted
    name: node_exporter
    enabled: true
  tags:
  - install