- name: Download grafana agent
  get_url:
    url: "https://github.com/grafana/agent/releases/download/v{{ ga_version }}/agent-linux-armv7.zip"
    dest: "/tmp/agent-linux-armv7.zip"
  tags:
  - install

- name: Unzip File
  unarchive:
    src: "/tmp/agent-linux-armv7.zip"
    dest: /tmp/
    remote_src: true

- name: Enable/Start grafana_agent
  systemd:
    daemon_reload: true
    state: stopped
    name: grafana_agent
    enabled: true
  tags:
  - install

- name: Remove old folder if present
  file:
    state: absent
    path: /opt/grafana_agent
  tags:
  - install

- name: Create folder
  file:
    state: directory
    path: /opt/grafana_agent
  tags:
  - install

- name: Move executable folder
  command: "mv /tmp/agent-linux-armv7 /opt/grafana_agent/"
  tags:
  - install

- name: Create grafana_agent User
  user:
    state: present
    name: grafana_agent
  tags:
  - install

- name: Set Permissions on grafana_agent
  file:
    path: /opt/grafana_agent
    owner: grafana_agent
    recurse: true
  tags:
  - install

- name: Copy Unit File
  copy:
    src: grafana_agent.service
    dest: /etc/systemd/system/grafana_agent.service
  tags:
  - install

- name: Template config file
  template:
    src: grafana_agent.yml.j2
    dest: /opt/grafana_agent/grafana_agent.yml

- name: Enable/Start grafana_agent
  systemd:
    daemon_reload: true
    state: restarted
    name: grafana_agent
    enabled: true
  tags:
  - install